"use strict";
const {
    POSSIBLE_SYMBOLS,
    CREDIT_RANGE,
    CHEAT_CHANCE,
    WIN_AMOUNT,
    INITIAL_CREDIT,
    NUMBER_OF_BLOCKS,
    SERVER_PORT,
    AUTHURIZED_CLIENT_PORT,
} = require('./general.js')

module.exports = {
    POSSIBLE_SYMBOLS,
    CREDIT_RANGE,
    CHEAT_CHANCE,
    WIN_AMOUNT,
    INITIAL_CREDIT,
    NUMBER_OF_BLOCKS,
    SERVER_PORT,
    AUTHURIZED_CLIENT_PORT,
}